import type { ProviderBrand } from './types';

export interface ProviderDescriptor {
  id: ProviderBrand;
  supportsName: boolean;
  supportsApiKey: boolean;
  supportsDisabled: boolean;
  supportsBaseUrl: boolean;
  baseUrlRequired: boolean;
  supportsProxyUrl: boolean;
  supportsPrefix: boolean;
  supportsModels: boolean;
  supportsHeaders: boolean;
  supportsExcludedModels: boolean;
  supportsPriority: boolean;
  supportsTestModel: boolean;
  supportsWebsockets: boolean;
  supportsCloak: boolean;
  supportsApiKeyEntries: boolean;
  /** Sheet 默认宽度 */
  sheetSize: 'md' | 'lg' | 'xl';
}

export const PROVIDER_DESCRIPTORS: Record<ProviderBrand, ProviderDescriptor> = {
  kimi: {
    id: 'kimi',
    supportsName: true,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: true,
    supportsProxyUrl: false,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: false,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: true,
    sheetSize: 'lg',
  },
  gemini: {
    id: 'gemini',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  interactions: {
    id: 'interactions',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  codex: {
    id: 'codex',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: true,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: true,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  xai: {
    id: 'xai',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: true,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: true,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  claude: {
    id: 'claude',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: true,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  claudeApi: {
    id: 'claudeApi',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: false,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: true,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  vertex: {
    id: 'vertex',
    supportsName: false,
    supportsApiKey: true,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: true,
    supportsPriority: true,
    supportsTestModel: false,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  openaiCompatibility: {
    id: 'openaiCompatibility',
    supportsName: true,
    supportsApiKey: false,
    supportsDisabled: true,
    supportsBaseUrl: true,
    baseUrlRequired: true,
    supportsProxyUrl: false,
    supportsPrefix: true,
    supportsModels: true,
    supportsHeaders: true,
    supportsExcludedModels: false,
    supportsPriority: true,
    supportsTestModel: true,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: true,
    sheetSize: 'lg',
  },
  code0: {
    id: 'code0',
    supportsName: false,
    supportsApiKey: false,
    supportsDisabled: true,
    supportsBaseUrl: false,
    baseUrlRequired: false,
    supportsProxyUrl: true,
    supportsPrefix: true,
    supportsModels: false,
    supportsHeaders: false,
    supportsExcludedModels: false,
    supportsPriority: true,
    supportsTestModel: false,
    supportsWebsockets: false,
    supportsCloak: false,
    supportsApiKeyEntries: false,
    sheetSize: 'md',
  },
  fennoAI: {
    id: 'fennoAI', supportsName: false, supportsApiKey: true, supportsDisabled: true,
    supportsBaseUrl: false, baseUrlRequired: false, supportsProxyUrl: true,
    supportsPrefix: true, supportsModels: true, supportsHeaders: false,
    supportsExcludedModels: false, supportsPriority: true, supportsTestModel: false,
    supportsWebsockets: false, supportsCloak: false, supportsApiKeyEntries: false, sheetSize: 'lg',
  },
  qiniuCloud: {
    id: 'qiniuCloud', supportsName: false, supportsApiKey: true, supportsDisabled: true,
    supportsBaseUrl: false, baseUrlRequired: false, supportsProxyUrl: true,
    supportsPrefix: true, supportsModels: true, supportsHeaders: false,
    supportsExcludedModels: false, supportsPriority: true, supportsTestModel: false,
    supportsWebsockets: false, supportsCloak: false, supportsApiKeyEntries: false, sheetSize: 'lg',
  },
  lmuAI: {
    id: 'lmuAI', supportsName: false, supportsApiKey: true, supportsDisabled: true,
    supportsBaseUrl: false, baseUrlRequired: false, supportsProxyUrl: true,
    supportsPrefix: true, supportsModels: true, supportsHeaders: false,
    supportsExcludedModels: false, supportsPriority: true, supportsTestModel: false,
    supportsWebsockets: false, supportsCloak: false, supportsApiKeyEntries: false, sheetSize: 'lg',
  },
};

export const PROVIDER_BRAND_ORDER: ProviderBrand[] = [
  'gemini',
  'codex',
  'claude',
  'vertex',
  'openaiCompatibility',
  'xai',
  'kimi',
  'claudeApi',
  'code0',
  'fennoAI',
  'qiniuCloud',
  'lmuAI',
  'interactions',
];

export const PROVIDER_PATHS: Record<ProviderBrand, string> = {
  kimi: '/ai-providers/kimi',
  gemini: '/ai-providers/gemini',
  interactions: '/ai-providers/interactions',
  codex: '/ai-providers/codex',
  xai: '/ai-providers/xai',
  claude: '/ai-providers/claude',
  claudeApi: '/ai-providers/claudeapi',
  vertex: '/ai-providers/vertex',
  openaiCompatibility: '/ai-providers/openai',
  code0: '/ai-providers/code0',
  fennoAI: '/ai-providers/fenno-ai',
  qiniuCloud: '/ai-providers/qiniu-cloud',
  lmuAI: '/ai-providers/lmuai',
};
